### PR TITLE
fix: modal confirmation external join rule setting and refactor code

### LINKED ISSUE #1352: Impossible d'ouvrir aux externes un salon privé existant
### Steps to reproduce

1. creer un salon privé
2. dans les settings du salon, l'ouvrir aux externes,
3. cliquer sur confirmer

Image
Image

4. l'option reste desactivée

Cela fonctionne sur mobile

PWA - Chrome
Version de Tchap : 4.16.2
Version crypto : Rust SDK 0.11.0 (404ca47), Vodozemac 0.9.0

### PR DESCRIPTION
**Pull request by MarcWadai**
fixes https://github.com/tchapgouv/tchap-web-v4/issues/1352

## Checklist

- [ ] Tests written for new code (and old code if feasible).
- [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
- [ ] Linter and other CI checks pass.
- [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

### CODE REVIEW

File: src/tchap/components/views/settings/TchapJoinRuleSettings.tsx [hunk 1]
```diff
@@ -132,18 +202,17 @@ const JoinRuleSettings = ({ room, promptUpgrade, aliasWarning, onError, beforeCh
...
                         _t("Are you sure you want to allow the externals to join this room ?"),
                     button: _t("action|ok"),
-                    onFinished: (confirmed) => {
-                        if (!confirmed) return;
-                        setTchapAccessRule({ rule: TchapRoomAccessRule.Unrestricted });
-                    },
                 });
+                const [ confirmed ] = await finished;
+                if (!confirmed) return;
+                setTchapAccessRule({ rule: TchapRoomAccessRule.Unrestricted });
```
Comment (MarcWadai) [inline src/tchap/components/views/settings/TchapJoinRuleSettings.tsx:215]: This is the use of the modal api, `onFinished` does not work anymore

**Review by MarcWadai — COMMENTED** [review]
This file is based on JoinRulesSetting, but replace with the customisation system. Here is a small refactor to be in line with the original file (update some classes, method etc)
