### PR TITLE
FIX : encode login hint

### LINKED ISSUE #1328: can not connect to proconnect with adress like aaaa+a2@gmail.com
### Steps to reproduce

1. try to connect to proconnect with adress with a '+' like  aaaa+a2@gmail.com
2. an error is thrown 👍 
```
code erreur : Y000400

id erreur : 7898dd32-291d-4e20-a9f9-596d8eec165f

message erreur : "Une erreur s'est produite, veuillez réessayer ultérieurement".
```

### Outcome

marche po 

sauf si je remplace le `+` par un `%2B` dans le champ email

### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by odelcroi**
fixes #1328 

tested : 
- [x] login
- [ ] UIA

Capture d’écran 2025-06-17 à 20 02 12
Capture d’écran 2025-06-17 à 20 02 37

## Checklist

- [ ] Tests written for new code (and old code if feasible).
- [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
- [ ] Linter and other CI checks pass.
- [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

### CODE REVIEW

File: src/components/views/auth/InteractiveAuthEntryComponents.tsx [hunk 1]
```diff
@@ -823,7 +824,7 @@ export class SSOAuthEntry extends React.Component<ISSOAuthEntryProps, ISSOAuthEn
         const { threepids } = await this.props.matrixClient.getThreePids();
         const email = threepids.find((t) => t.medium === "email")?.address;
         // in the url, there is alreay a query param for sessionId, so we use & instead of ?
-        this.ssoUrl = this.ssoUrl + "&login_hint=" + email;
+        this.ssoUrl = this.ssoUrl + "&" + encodeParams({"login_hint" :email});;
```
Comment (odelcroi) [inline src/components/views/auth/InteractiveAuthEntryComponents.tsx]:
```suggestion
        this.ssoUrl = this.ssoUrl + "&" + encodeParams({"login_hint" :email});
```

**Review by mcalinghee — APPROVED** [review]

**Review by MarcWadai — APPROVED** [review]
